# Generated by Django 5.1.1 on 2024-09-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ИМЯ')),
                ('email', models.CharField(max_length=255, verbose_name='E-MAIL')),
                ('password', models.CharField(max_length=63, verbose_name='ПАРОЛЬ')),
            ],
        ),
    ]
