# Generated by Django 5.1.1 on 2024-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.TextField(blank=True, null=True, verbose_name='Резюме'),
        ),
    ]
