# Generated by Django 5.1.1 on 2024-10-09 17:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume',
        ),
        migrations.AddField(
            model_name='employer',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес компании'),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Отрасль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='inn',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='desired_job_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Желаемая категория работы'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='desired_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Желаемое место работы'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='desired_salary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ожидаемая зарплата'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Интересы'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='Владеемые языки'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на портфолио'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jobseeker_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
