# Generated by Django 5.1.1 on 2024-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('users', '0007_employer_rating_jobseeker_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Работодатель'), ('seeker', 'Соискатель')], default='Работодатель', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='manager.skill'),
        ),
    ]
