# Generated by Django 5.1.1 on 2024-10-29 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_employer_rating_alter_review_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='source',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Просмотрена'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to=settings.AUTH_USER_MODEL),
        ),
    ]
