# Generated by Django 5.1.1 on 2024-10-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_date_of_creation'),
        ('users', '0006_remove_jobseeker_resume_employer_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный Email'),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(default='Полная занятость', max_length=50, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('it', 'IT'), ('hr', 'HR'), ('finance', 'Финансы'), ('marketing', 'Маркетинг'), ('trade', 'Торговля')], default='it', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='job',
            name='resps',
            field=models.BigIntegerField(default=0, verbose_name='Кол-во откликов'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_response', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('employer_feedback', models.TextField(blank=True, verbose_name='Обратная связь')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobs.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.jobseeker')),
            ],
            options={
                'unique_together': {('job', 'job_seeker')},
            },
        ),
    ]
