# Generated by Django 5.1.1 on 2024-10-09 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_feature'),
        ('users', '0006_remove_jobseeker_resume_employer_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='employer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_job', to='jobs.job'),
        ),
    ]
