# Generated by Django 5.1.1 on 2024-10-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_response_employer_alter_feature_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full', 'Полная занятость'), ('half', 'Неполная занятость'), ('free', 'Удаленно')], default='full', max_length=50, verbose_name='Тип занятости'),
        ),
    ]
