# Generated by Django 5.1.1 on 2024-10-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='employer',
        ),
        migrations.AlterField(
            model_name='response',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='response',
            name='employer_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Обратная связь'),
        ),
    ]
