# Generated by Django 5.1.1 on 2024-10-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_response_employer_alter_response_cover_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('it', 'IT'), ('hr', 'HR'), ('finance', 'Финансы'), ('marketing', 'Маркетинг'), ('trade', 'Торговля')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='vacancies', to='jobs.skill'),
        ),
    ]
