# Generated by Django 5.1.1 on 2024-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_skill_remove_job_requirements_alter_job_industry_and_more'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='vacancies', to='manager.skill'),
        ),
    ]
