# Generated by Django 5.1.1 on 2024-10-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_delete_skill_alter_job_skills'),
        ('users', '0008_remove_jobseeker_skills_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_exp',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='response',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to='users.jobseeker'),
        ),
    ]
