# Generated by Django 5.1.1 on 2024-10-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_response_job_seeker'),
        ('jobs', '0011_job_work_exp_alter_response_job_seeker'),
    ]

    operations = [
    ]
